sudo: required

services:
  - docker

## Make sure all containers build without error.
before_install: 
  - docker build -t mrchypark/tfr-baseimage tfr-base/.
  - docker build -t mrchypark/tfr-rstudio tfr-rstudio/.

## A few simple / crude tests
script:
  - docker run -ti mrchypark/tfr-baseimage python -V
  - docker run -d --name rstudio mrchypark/tfr-rstudio
  - sleep 5 && docker ps | grep rstudio
  - docker rm -f $(docker ps -a -q)
